version: "3.0"
services:
  db:
    container_name: "db"
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=maxrbv
      - RABBITMQ_DEFAULT_PASS=maxrbv
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "15672:15672"